project:
  type: website

website:
  title: "liamgilbey"
  description: "Liam Gilbey's personal website"
  favicon: "figures/liam.png"
  google-analytics: ""
  twitter-card:
    creator: "@liam__gilbey"
  site-url: https://liamgilbey.github.io
  repo-url: https://github.com/liamgilbey/liamgilbey.github.io
  sidebar:
    title: false
    search: true
    style: "docked"
    border: false
    tools: 
      - icon: github
        href: https://github.com/liamgilbey
      - icon: twitter
        href: https://twitter.com/liam__gilbey
      - icon: linkedin
        href: https://linkedin.com/in/liam-gilbey
    background: primary
    contents: 
      - text: "{{< fa house >}} Home"
        href: index.qmd
      - text: "{{< fa brands r-project >}} Projects"
        href: projects.qmd
      - text: "{{< fa pen >}} Blog"
        href: blog.qmd 
      - text: "{{< fa envelope >}} Contact"
        href: mailto:liam.gilbey@gmail.com

format:
  html:
    theme:
      - sandstone
      - theme.scss

execute: 
  freeze: auto